sudo: require

install:
  # LyX
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq
  - sudo apt-get install lyx

script:
  - lyx --export epub travis_lyx_epub.lyx
  # Check if the EPUB has been created
  - if [ ! -e travis_lyx_epub.epub ]; then exit 1; fi